app:
  max_async_workers: 1

ai:
  # llm_provider: lmstudio
  # llm_provider: request  
  llm_provider: openai  
  model: "-"
  temperature: 0.5
  base_url: "https://api.proxyapi.ru/openrouter/v1"
  # base_url: "https://openrouter.ai/api/v1"
  max_generate_retries: 3
  max_fix_attempts: 4
  target_line_coverage: 60

logger:
  log_out: both
  console_level: debug
  file_level: debug
  log_file: logs/app.log